name: flutter_markdown_example
description: Demonstrates how to use the flutter_markdown_plus package.
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  flutter_markdown_plus: ^1.0.2
  flutter_markdown_plus_latex: ^1.0.0
  markdown: ^7.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_markdown_plus:
    path: ../

flutter:
  assets:
    - assets/

  fonts:
    - family: 'Roboto Mono'
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf

  uses-material-design: true

dartfmt:
  line_length: 120
